### ISSUE TITLE
Display queue information in project page

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#18]

**Comment by ewels** [comment]
If this involves any plotting, I recommend [HighCharts](http://www.highcharts.com/) instead of D3, as has been used in the past.

Bootstrap [progress bars](http://getbootstrap.com/components/#progress-stacked) may be useful for something simpler.

**Comment by pekrau** [comment]
Yes, I was also thinking of D3, but haven't looked at it yet.

**Comment by ewels** [comment]
Yup - genomics status had lots of stuff built in D3. I think HighCharts is a lot easier to write code for with nicer defaults. Pus the documentation is excellent and stuffed with JSFiddle demos which are brilliant starting points.

I've _(and now more collectively we)_ have been slowly replacing the genstat plots with highcharts since I got here... :grinning:

**Comment by pekrau** [comment]
Done.
