### ISSUE TITLE
What to put into field "Amount of sequencing data required per sample"?

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#444]
Love Dalén: It’s unclear what you mean by “Amount of sequencing data required per sample”. If one has just ordered X number of lanes, why would this need to be specified?

Sigh. We have discussed this, haven't we. Is the info text for the field not good enough?

What do you think? @ormestad @ellenordevine

**Comment by ormestad** [comment]
We could change the descriptive text from "Please specify the amount of data required per sample" to "If you're unsure of how many lanes are needed please specify the amount of data required per sample".

In that case this should be an optional field, but the problem is that one of the two fields must be filled in so both should not be optional - it should be either one or the other...

**Comment by pekrau** [comment]
Used the suggested text, and made it optional.
