### ISSUE TITLE
Field conditional visibility

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#67]
Open up and close down hierarchical branches of the field tree, as appropriate.

jQuery code:
```
var classnames = {
    'Condition Value One': 'class1',
    'Condition Value Two': 'class2'
}
$('.myDropDown').change(function(){
    var thisVal = $(this).val();
    var thisClass = classnames[thisVal];
    $('.conditional-field').hide(); // Hide everything that has been shown by previous choices
    $('.'+thisClass').show(); // Show the new group
});
```

HTML code:
```
<form><select class="myDropDown"><option>Condition Value One</option><option>Condition Value Two</option></select></form>
<p>This is always shown.</p>
<p class="conditional-field class1">This is only shown for <em>Condition Value One</em></p>
<p class="conditional-field class2">This is only shown for <em>Condition Value Two</em></p>
```

If you want to get fancy, you can extend this to have fields / objects which are visible for sets of values very easily:
```
var classnames = {
    'Condition Value One': '.class1',
    'Condition Value Two': '.class2',
    'Condition Value Three': '.class1 .class2'
}
$('.myDropDown').change(function(){
    $('.conditional-field').hide(); // Hide everything that has been shown by previous choices
    $(classnames[$(this).val()]).show(); // Show the new group
});
```

**Comment by ewels** [comment]
Note that if we're just showing and hiding form inputs, everything will still be submitted on form submission. You can handle this by:

- intercepting and handling the submission with jQuery again
- actually adding / removing elements instead of showing / hiding them
- handling the logic server side
- saving everything but ignoring it if not applicable

Also, see [this blog post](http://www.mediamilan.com/tutos/conditional-form-using-jquery/) for a more verbose description of my slack messages above..

**Comment by pekrau** [comment]
Chose a different implementation. The JS is static and uses information provided in data attributes of the HTML elements to find those to set visibility of.
